Fix a build break due to a missing Semigroup constraint:
    sbt> brushfireFinatra/compile
    [info] Updating {file:/source/brushfire/}brushfireFinatra...
    [info] Resolving org.fusesource.jansi#jansi;1.4 ...
    [info] Done updating.
    [info] Compiling 2 Scala sources to /source/brushfire/brushfire-finatra/target/scala-2.10/classes...
    [error] /source/brushfire/brushfire-finatra/src/main/scala/com/stripe/brushfire/finatra/BrushfireServer.scala:13: Cannot find Semigroup type class for T
    [error]         val score = voter.predict(trees, row)
    [error]                                  ^
    [error] /source/brushfire/brushfire-finatra/src/main/scala/com/stripe/brushfire/finatra/BrushfireServer.scala:25: Cannot find Semigroup type class for T
    [error]     score[K, V, T, P](root, trees.toList, voter)(fn)
    [error]                                                 ^
    [error] (brushfireFinatra/compile:compile) Compilation failed
    [error] Total time: 1 s, completed Sep 1, 2015 4:22:41 PM